const errorMsg = {
    errorEmail: '이메일을 확인해 주세요',
    emptyEmail: '이메일을 입력해 주세요',
    emptyName: '이름을 입력해 주세요',
    emptyPhone: '전화번호를 입력해 주세요',
    validPhone: '정확한 전화번호를 입력해 주세요',
    verifyMobile: '휴대폰 인증을 해주세요',
    verifyOTP: 'OTP인증을 해주세요',
    invalidInput: '정확하지 않은 정보 입니다',
    nameExists: '등록되어있지 않은 전화번호/이름 입니다',
    validOTP: '정확한 OTP 번호를 입력해 주세요',
    OTPCheck: '번호가 일치하지 않습니다',
    emptyPassword: '비밀번호를 입력해 주세요',
    emptyConfirmPassword: '비밀번호 확인을 입력해 주세요',
    matchPassword: '비밀번호가 일치하지 않습니다',
    passwordError: '정확하지 않은 정보 입니다.',
    termsError : "필수 약관에 동의해 주세요",
    personalError : "필수 약관에 동의해 주세요",
    emptyDepartment : "부서명을 입력해 주세요",
    emptyEmailVerification : "이메일 인증번호를 입력해 주세요",
    wrongEmailVerifyCode : "이메일 인증번호가 틀렸습니다",
    emailUnverified : "이메일 인증이 완료됐습니다",
    emptyRank : "직급을 입력해 주세요",
    matchCurrentNewPassword:"현재 비밀번호와 새 비밀번호를 다르게 입력해주세요",
    emptyCompanyCode: "기업코드를 입력해주세요",
    verifyCompanyCode: "인증을 해주세요",
    companyCodeExist: "유효한 기업코드가 아닙니다",
    inquiry_title: "문의 제목을 입력해 주세요",
    inquiry_type: "문의 타입을 입력해 주세요",
    inquiry_details:"설명란을 입력해주세요",
    title: "제목을 입력해 주세요",
    boardName: "게시판명을 입력해 주세요",
    schedule_title: "제목을 입력해주세요",
    scheduletitleLength:'최대 20자까지 입력가능합니다.',
    schedule_details:'상세 정보를 입력해주세요',
    scheduleDetailLength:'일정 상세 내용을 입력해주세요',
    schedule_start_date: "시작일시를 입력해주세요",
    validDate:'Start date and time should be greater than or equal to current date',
    schedule_end_date:'End date and time should be geater than or equal to start date',
    emptyEndDate:'종료일시를 입력해주세요',
    tab_name: "구성도명을 입력해주세요",
    tab_name_length:'최대 10자까지 입력가능합니다.',
    emptyReason : "환불사유를 입력해주세요",
    emptyAccount: "환불계좌 입력해주세요",
    emptyTemplate:'템플릿명을 입력해주세요',
    sub_type_id:'문의유형을 선택해주세요',
    numericCheck:'정확하지 않은 정보 입니다',
    reasonText: '거절사유를 입력해주세요',
    implementation_cost: "구현내용을 입력해주세요",
    implementation_difficulty: "구현난이도를 입력해주세요",
    action_schedule: "일정을 입력해주세요",
}

const status = {
    verifiedOTP: 'OTP verified',
    verifiedEmailCode: '인증되었습니다'
}

export {errorMsg, status};